# Generated by Django 6.0.1 on 2026-01-16 09:59

from decimal import Decimal
from typing import ClassVar

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = []

    operations: ClassVar = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="Сумма выплаты",
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Сумма выплаты",
                    ),
                ),
                (
                    "currency",
                    models.TextField(
                        choices=[
                            ("RUB", "Российский рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                        ],
                        db_comment="Валюта",
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "recipient_details",
                    models.TextField(
                        db_comment="Реквизиты получателя", verbose_name="Реквизиты получателя"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("NEW", "Новая"),
                            ("PROCESSING", "Обработка заявки"),
                            ("COMPLETED", "Заявка обработана"),
                            ("FAILED", "Ошибка обработки"),
                            ("CANCELLED", "Отменена"),
                        ],
                        default="PROCESSING",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.CharField(
                        db_comment="Комментарий",
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "db_table": "payouts",
                "db_table_comment": "Заявки на выплату",
            },
        ),
    ]
